CallibrationRegister/Models/Field.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CallibrationRegister.Models
{
    public class Field
    {
        public string Id { get; set; }
        public string DisplayName { get; set; }
        public uint SortOrder { get; set; }
        public string DataType { get; set; }
    }
}

CallibrationRegister/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CallibrationRegister.Models
{
    public class Tag
    {
        public string Name { get; set; }

        public string TagType { get; set; }

        public string Fields { get; set; }
    }
}

CallibrationRegister/Models/TagType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CallibrationRegister.Models
{
    public class TagType
    {
        public string Name { get; set; }

        public ICollection<Field> TagFields { get; set; }

        public ICollection<Field> CallibrationFields { get; set; }
    }
}

CallibrationRegister/Models/TagTypes.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CallibrationRegister.Models
{
    public class TagTypes
    {
        public static IEnumerable<TagType> Get()
        {
            return new List<TagType>()
            {
                new TagType()
                {
                    Name = "PH",
                    TagFields = GetTagFieldsFromJson(),
                    CallibrationFields = GetCallibrationFieldsFromJson()
                },
                new TagType {
                    Name = "FIT",
                    TagFields = GetTagFieldsFromJson2(),
                    CallibrationFields = GetCallibrationFieldsFromJson2()
                }
            };
        }

        private static ICollection<Field> GetTagFieldsFromJson()
        {
            var json = @"
            [
                {
                    ""Id"" : ""tag-field-param-one"",
                    ""DisplayName"" : ""Tag Parameter One"",
                    ""SortOrder"" : 1,
                    ""DataType"" : ""string""
                },
                {
                    ""Id"" : ""tag-field-param-two"",
                    ""DisplayName"" : ""Tag Parameter Two"",
                    ""SortOrder"" : 2,
                    ""DataType"" : ""number""
                },
                {
                    ""Id"" : ""tag-field-param-three"",
                    ""DisplayName"" : ""Tag Field Three"",
                    ""SortOrder"" : 3,
                    ""DataType"" : ""date""
                }
            ]
            ";

            return JsonConvert.DeserializeObject<ICollection<Field>>(json);
        }

        private static ICollection<Field> GetCallibrationFieldsFromJson()
        {
            var json = @"
            [
                {
                    ""Id"" : ""cal-field-calFieldOne"",
                    ""DisplayName"" : ""Cal Field One"",
                    ""SortOrder"" : 1,
                    ""DataType"" : ""string""
                },
                {
                    ""Id"" : ""cal-field-calFieldTwo"",
                    ""DisplayName"" : ""Cal field Two"",
                    ""SortOrder"" : 2,
                    ""DataType"" : ""number""
                },
                {
                    ""Id"" : ""cal-field-calFieldThree"",
                    ""DisplayName"" : ""Cal Field Three"",
                    ""SortOrder"" : 3,
                    ""DataType"" : ""date""
                }
            ]
            ";

            return JsonConvert.DeserializeObject<ICollection<Field>>(json);
        }

        private static ICollection<Field> GetTagFieldsFromJson2()
        {
            var json = @"
            [
                {
                    ""Id"" : ""tag-field-param-one-fit"",
                    ""DisplayName"" : ""Tag Parameter One FIT"",
                    ""SortOrder"" : 1,
                    ""DataType"" : ""string""
                }
            ]
            ";

            return JsonConvert.DeserializeObject<ICollection<Field>>(json);
        }

        private static ICollection<Field> GetCallibrationFieldsFromJson2()
        {
            var json = @"
            [
                {
                    ""Id"" : ""cal-field-fiel-one-fit"",
                    ""DisplayName"" : ""Cal Field One FIT"",
                    ""SortOrder"" : 1,
                    ""DataType"" : ""string""
                }
            ]
            ";

            return JsonConvert.DeserializeObject<ICollection<Field>>(json);
        }
    }
}

CallibrationRegister/Models/Tags.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CallibrationRegister.Models
{
    public class Tags
    {
        private static List<Tag> _tags = new List<Tag>();

        public static IEnumerable<Tag> Get()
        {
            return _tags;
        }

        public static Tag GetByName(string name)
        {
            return _tags.SingleOrDefault(x => x.Name == name);
        }
        
        public static void Add(Tag tag)
        {
            _tags.Add(tag);
        }
    }
}

CallibrationRegister/Controllers/TagController.cs
using CallibrationRegister.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CallibrationRegister.Controllers
{
    public class TagController : Controller
    {
        // GET: Tag
        public ActionResult Index()
        {
            ViewBag.TagTypes = TagTypes.Get();
            var tags = Tags.Get();
            return View(tags);
        }

        public ActionResult Create(string tagTypeName)
        {
            var tagType = TagTypes.Get().SingleOrDefault(x => x.Name == tagTypeName); 
            
            return View(tagType);
        }

        [HttpPost]
        public ActionResult Create(FormCollection form)
        {
            var tag = new Tag()
            {
                Name = form["name"],
                TagType = form["tagType"]
            };

            var fields = new Dictionary<string, object>();
            foreach (var key in form.AllKeys.Where(x => x.StartsWith("tag-field-")))
            {
                fields.Add(key, form[key]);
            }

            tag.Fields = JsonConvert.SerializeObject(fields);

            Tags.Add(tag);

            return RedirectToAction("Index");
        }
    }
}

CallibrationRegister/Controllers/TagTypeController.cs
using CallibrationRegister.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CallibrationRegister.Controllers
{
    public class TagTypeController : Controller
    {
        // GET: TagType
        public ActionResult Index()
        {
            var tagTypes = TagTypes.Get();
            return View(tagTypes);
        }

        // GET: TagType/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TagType/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TagType/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TagType/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TagType/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TagType/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TagType/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CallibrationRegister/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type = 'text/javascript' >
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'8092eb8b-45d5-468f-b57f-3ec627e8dc99'
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Tag", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Tags", "Index", "Tag")</li>
                    <li>@Html.ActionLink("Tag Types", "Index", "TagType")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CallibrationRegister/Views/Tag/Create.cshtml
@model CallibrationRegister.Models.TagType

@{
    ViewBag.Title = "Create " + Model.Name + " Tag";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    @Html.Hidden("tagType", Model.Name);

    <div class="form-group">
        <label>Tag Name</label>
        <input class="form-control input-sm" type="text" name="name" />
    </div>

    <hr />

    <h4>Tag Fields</h4>
    <div class="form-horizontal">
        @foreach (var tagField in Model.TagFields.OrderBy(x => x.SortOrder))
        {
            <div class="form-group">
                <label>@tagField.DisplayName</label>
                <input class="form-control input-sm" type="@tagField.DataType" name="@tagField.Id" />
            </div>
        }
    <hr />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CallibrationRegister/Views/Tag/Index.cshtml
@model IEnumerable<CallibrationRegister.Models.Tag>

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

@using (Html.BeginForm("Create", "Tag", FormMethod.Get))
{
    @Html.DropDownList("tagTypeName", new SelectList(ViewBag.TagTypes, "Name", "Name"), new { @class = "form-control input-sm" })

    <input class="btn btn-sm btn-success" type="submit" value="Create new Tag"/>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TagType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fields)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TagType)
        </td>
        <td>
            <pre><code>@Html.DisplayFor(modelItem => item.Fields)</code></pre>
        </td>
    </tr>
}

</table>

CallibrationRegister/Views/TagType/Index.cshtml
@model IEnumerable<CallibrationRegister.Models.TagType>
@using Newtonsoft.Json;

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Tag Fields
        </th>
        <th>
            Callibration Fields
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            <pre><code>@JsonConvert.SerializeObject(item.TagFields, Formatting.Indented)</code></pre>
        </td>
        <td>
            <pre><code>@JsonConvert.SerializeObject(item.CallibrationFields, Formatting.Indented)</code></pre>
        </td>
    </tr>
}

</table>