SSWA.CalibrationRegister.Web/Controllers/CalibrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SSWA.CalibrationRegister.Web.Services;
using Microsoft.AspNetCore.Authorization;
using SSWA.CalibrationRegister.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ViewFeatures.Internal;
using System.Linq.Expressions;
using Newtonsoft.Json;

namespace SSWA.CalibrationRegister.Web.Controllers
{
    [Authorize]
    public class CalibrationController : Controller
    {
        private readonly CalibrationService _calibrationService;
        private readonly TagService _tagService;

        public CalibrationController(CalibrationService calibrationService, TagService tagService)
        {
            _calibrationService = calibrationService;
            _tagService = tagService;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = await _calibrationService.GetCalibrationListViewModelAsync();
            return View(viewModel);
        }

        // GET: Calibration/Tag
        public async Task<ActionResult> Tag(int? page = 1, int? tagTypeId = null, string tagName = null, string tagDescription = null)
        {
            var viewModel = await _tagService.GetTagListViewModelAsync(page, tagTypeId, tagName, tagDescription);
            return View(viewModel);
        }

        // GET: Calibration/History
        public async Task<ActionResult> History(int tagId)
        {
            var viewModel = await _calibrationService.GetCalibrationHistoryViewModelAsync(tagId);
            if (viewModel.GetType() == typeof(CalibrationHistoryStandardViewModel))
            {
                var stdViewModel = (viewModel as CalibrationHistoryStandardViewModel);
                return View("HistoryStandard", viewModel);
            }

            if (viewModel.GetType() == typeof(CalibrationHistoryChlorineViewModel))
            {
                var stdViewModel = (viewModel as CalibrationHistoryChlorineViewModel);
                return View("HistoryChlorine", viewModel);
            }

            if (viewModel.GetType() == typeof(CalibrationHistoryFlowViewModel))
            {
                var stdViewModel = (viewModel as CalibrationHistoryFlowViewModel);
                return View("HistoryFlow", viewModel);
            }

            return View();
        }

        // GET: Calibration/Create
        [Authorize(Policy = "create:calibrations")]
        public async Task<ActionResult> Create(int tagId)
        {
            var viewModelResult = await _calibrationService.GetCreateCalibrationViewModelAsync(tagId);

            if (viewModelResult.IsValid)
            {
                return View(viewModelResult.ViewModel);
            }
            else
            {
                return View("CreateValidationError", viewModelResult);
            }

        }

        // POST: Calibration/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "create:calibrations")]
        public async Task<ActionResult> Create(int tagId, CreateCalibrationViewModel viewModel, IFormCollection formCollection)
        {
            try
            {
                if (viewModel.VerificationOnly)
                {
                    viewModel.RecordNumber = "VER." + GetHashCode();
                }
                else
                {
                    viewModel.RecordNumber = "CAL." + GetHashCode();
                }
                
                var fields = new Dictionary<string, string>();
                for (int i = 0; i < viewModel.CalibrationFields.Count; i++)
                {
                    var value = viewModel.CalibrationFields[i].Value;
                    var key = viewModel.CalibrationFields[i].Id;
                    var type = viewModel.CalibrationFields[i].DataType;

                    if (!string.IsNullOrWhiteSpace(value) && type == "number" && !decimal.TryParse(value, out decimal decimalValue))
                    {
                        ModelState.AddModelError<CreateCalibrationViewModel, string>(x => x.CalibrationFields[i].Value, "This field must be a number");
                        continue;
                    }

                    if (!string.IsNullOrWhiteSpace(value) && type == "checkbox" && !bool.TryParse(value, out bool boollValue))
                    {
                        ModelState.AddModelError<CreateCalibrationViewModel, string>(x => x.CalibrationFields[i].Value, "This field must be checked or unchecked");
                        continue;
                    }

                    fields.Add(key, value);
                }

                if (ModelState.IsValid)
                {
                    await _calibrationService.CreateCalibrationAsync(viewModel, fields);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    var newViewModel = await _calibrationService.GetCreateCalibrationViewModelAsync(viewModel.TagID, viewModel, formCollection);
                    return View(newViewModel);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Could not add calibration");
                var newViewModel = await _calibrationService.GetCreateCalibrationViewModelAsync(viewModel.TagID, viewModel, formCollection);
                return View(newViewModel);
            }
        }

        public void Report()
        {
            //LocalReport report = new LocalReport();
        }
    }
}

SSWA.CalibrationRegister.Web/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SSWA.CalibrationRegister.Web.Services;
using SSWA.CalibrationRegister.Web.Models;
using SSWA.CalibrationRegister.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace SSWA.CalibrationRegister.Web.Controllers
{
    [Authorize]
    public class TagController : Controller
    {
        private TagService _tagService;
        private CalibrationDbContext _context;

        public TagController(TagService tagService, CalibrationDbContext context)
        {
            _tagService = tagService;
            _context = context;
        }

        // GET: Tag
        public async Task<ActionResult> Index(int? page = 1, int? tagTypeId = null, string tagName = null, string tagDescription = null)
        {
            var viewModel = await _tagService.GetTagListViewModelAsync(page, tagTypeId, tagName, tagDescription);
            return View(viewModel);
        }

        // GET: Tag/Create
        [Authorize(Policy = "create:tags")]
        public async Task<ActionResult> Create(int tagTypeId)
        {
            var viewModel = await _tagService.GetCreateTagViewModelAsync(tagTypeId);
            return View(viewModel);
        }

        // POST: Tag/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "create:tags")]
        public async Task<ActionResult> Create(CreateTagViewModel viewModel, IFormCollection formCollection)
        {
            try
            {
                var fields = new Dictionary<string, string>();
                foreach (var key in formCollection.Keys.Where(x => x.StartsWith("tag_")))
                {
                    var value = formCollection[key].ToString();
                    fields.Add(key, value);
                }

                await _tagService.CreateTagAsync(viewModel, fields);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Tag/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var viewModel = await _tagService.GetEditTagViewModelAsync(id);
            return View(viewModel);
        }

        // POST: Tag/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, EditTagViewModel viewModel, IFormCollection formCollection)
        {
            try
            {
                var fields = new Dictionary<string, string>();
                foreach (var key in formCollection.Keys.Where(x => x.StartsWith("tag_")))
                {
                    var value = formCollection[key].ToString();
                    fields.Add(key, value);
                }

                await _tagService.UpdateTagAsync(id, viewModel, fields);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Tag/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Tag/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SSWA.CalibrationRegister.Web/Views/Calibration/Create.cshtml
@model SSWA.CalibrationRegister.Web.Models.CreateCalibrationViewModel

@{
    ViewData["Title"] = "Create";
}

<div classs="row">
    <div class="col-md-12">
        <h3>Calibrations &rsaquo; New &rsaquo; @Model.TagName</h3>
        <hr />
    </div>
</div>
<form asp-action="Create" asp-route-tagId="@Model.TagID">
    <div class="row">
        <div class="col-md-5">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="TagID" type="hidden" />
            <input asp-for="DocumentNumber" type="hidden" class="form-control input-sm" />
            <input asp-for="Revision" type="hidden" class="form-control input-sm" />
            <input asp-for="IssuedAt" type="hidden" class="form-control input-sm" />
        </div>
    </div>
    <h4>Tag Details</h4>
    <div class="row">
        <div class="col-md-1">
            <div class="form-group">
                <label asp-for="TagName" class="control-label"></label>
                <input disabled asp-for="TagName" class="form-control input-sm" />
            </div>
        </div>
        <div class="col-md-5">
            <div class="form-group">
                <label asp-for="TagDescription" class="control-label"></label>
                <input disabled asp-for="TagDescription" class="form-control input-sm" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="TagMake" class="control-label"></label>
                <input disabled asp-for="TagMake" class="form-control input-sm" />
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="TagModel" class="control-label"></label>
                <input disabled asp-for="TagModel" class="form-control input-sm" />
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="TagSerialNumber" class="control-label"></label>
                <input disabled asp-for="TagSerialNumber" class="form-control input-sm" />
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="TagReferenceDrawing" class="control-label"></label>
                <input disabled asp-for="TagReferenceDrawing" class="form-control input-sm" />
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="TagProcedure" class="control-label"></label>
                <input disabled asp-for="TagProcedure" class="form-control input-sm" />
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="TagDataSheet" class="control-label"></label>
                <input disabled asp-for="TagDataSheet" class="form-control input-sm" />
            </div>
        </div>
    </div>
    <h4>Tag Values</h4>
    <div class="row">
        @for (int i = 0; i < Model.TagFields.Count; i++)
        {
            <div class="col-md-3">
                <div class="form-group">
                    <input asp-for="TagFields[i].Id" type="hidden" />
                    <label class="control-label">@Model.TagFields[i].DisplayName</label>
                    <input disabled asp-for="@Model.TagFields[i].Value" class="form-control input-sm" />
                </div>
            </div>
        }
    </div>
    <hr />
    <h4>Equipment</h4>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <fieldset class="form-add-equipment">
                    <div class="col-md-12">
                        <div class="form-inline">
                            <div class="form-group">
                                <select id="Equipments" class="form-control input-sm" asp-items="Model.EquipmentSelectList"></select>
                            </div>
                            <div class="form-group">
                                <button type="button" class="btn btn-sm btn-add-item btn-primary">Add Equipment</button>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <div class="add-equipment">
                        @for (int i = 0; i < Model.Equipment.Count; i++)
                        {
                            <div class="form-group row add-item">
                                <div class="col-sm-6">
                                    <input asp-for="Equipment[i].ID" type="hidden" />
                                    <input disabled asp-for="Equipment[i].MakeModel" placeholder="MakeModel" class="form-control input-sm" />
                                    <span asp-validation-for="Equipment[i].MakeModel" class="text-danger" />
                                </div>
                                <div class="col-sm-1">
                                    <button type="button" role="button" class="btn btn-sm btn-remove-item" data-toggle="tooltip" title="Remove Item"><span class="glyphicon glyphicon-minus"></span></button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <h4>Calibration</h4>
    <div class="row">       
        @for (int i = 0; i < Model.CalibrationFields.Count; i++)
        {
            <div class="col-md-3">
                <div class="form-group">
                    <input asp-for="CalibrationFields[i].Id" type="hidden" />
                    <input asp-for="CalibrationFields[i].DataType" type="hidden" />
                    <label class="control-label">@Model.CalibrationFields[i].DisplayName</label>
                    <input asp-for="CalibrationFields[i].Value" type="@Model.CalibrationFields[i].DataType" class="form-control input-sm" />
                    <span asp-validation-for="CalibrationFields[i].Value" class="text-danger"></span>
                </div>
            </div>
        }
    </div>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="WorkOrderNumber" class="control-label"></label>
                <input asp-for="WorkOrderNumber" class="form-control input-sm" />
                <span asp-validation-for="WorkOrderNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TestedAt" class="control-label"></label>
                <input asp-for="TestedAt" class="form-control input-sm" />
                <span asp-validation-for="TestedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TestedBy" class="control-label"></label>
                <input asp-for="TestedBy" class="form-control input-sm" />
                <span asp-validation-for="TestedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <textarea rows="10" asp-for="Comments" class="form-control input-sm"></textarea>
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">
            <div class="form-group">
                <label asp-for="VerificationOnly" class="control-label"></label>
                    <input asp-for="VerificationOnly" class="form-control input-sm" />
                <span asp-validation-for="VerificationOnly" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(document).ready(function () {
            var wrapper = $('.add-equipment');

            $('#Equipments').change(function () {

                let id = $('#Equipments').val();
                let makeModel = $('#Equipments').find(":selected").text();

                let index = $('.add-equipment').children().length;
                let template = $('<div class="form-group row add-item">' +
                    '<div class="col-sm-6">' +
                    '<input name="Equipment[' + index + '].ID" type="hidden" value="' + id + '" />' +
                    '<input disabled name="Equipment[' + index + '].MakeModel" placeholder="MakeModel" class="form-control input-sm" value="' + makeModel + '" />' +
                    '<span asp-validation-for="Equipment[' + index + '].MakeModel" class="text-danger" />' +
                    '</div>' +
                    '<div class="col-sm-1">' +
                    '<button type="button" role="button" class="btn btn-sm btn-remove-item" data-toggle="tooltip" title="Remove Item"><span class="glyphicon glyphicon-minus"></span></button>' +
                    '</div>' +
                    '</div>')

                template.appendTo(wrapper);

                $('.add-item .btn-remove-item').show();
            });

            $(".btn-add-item").click(function (e) {
               
                e.preventDefault();
                let id = $('#Equipments').val();
                let makeModel = $('#Equipments').find(":selected").text();

                let index = $('.add-equipment').children().length;
                let template = $('<div class="form-group row add-item">' +
                    '<div class="col-sm-6">' +
                        '<input name="Equipment[' + index + '].ID" type="hidden" value="' + id + '" />' +
                        '<input disabled name="Equipment[' + index + '].MakeModel" placeholder="MakeModel" class="form-control input-sm" value="' + makeModel +'" />' +
                        '<span asp-validation-for="Equipment['+index+'].MakeModel" class="text-danger" />' +
                    '</div>' +
                    '<div class="col-sm-1">' +
                        '<button type="button" role="button" class="btn btn-sm btn-remove-item" data-toggle="tooltip" title="Remove Item"><span class="glyphicon glyphicon-minus"></span></button>' +
                    '</div>' +
                '</div>')

                template.appendTo(wrapper);

                $('.add-item .btn-remove-item').show();
            });

            $(document).on('click', '.btn-remove-item', function (e) {
                e.preventDefault();
                $(this).parents('.add-item').remove();
            });

        });
    </script>
}

SSWA.CalibrationRegister.Web/Views/Calibration/CreateValidationError.cshtml
@model SSWA.CalibrationRegister.Web.Models.ViewModelResult<CreateCalibrationViewModel>
@{
    ViewData["Title"] = "Warning";
}

<h3 class="text-warning">@Model.ViewModel.TagName Warning</h3>
<br />
<br />
<p>Please go <strong>@Html.ActionLink("HERE", "Edit", "Tag", new { id = Model.ViewModel.TagID }, new { target = "_blank" })</strong> to fix the following errors before entering a calibration.</p>
<br />
<br />
<h4>Issues</h4>

@foreach (var message in Model.Messages)
{
    <div class="alert alert-warning">
        @message
    </div>
}

SSWA.CalibrationRegister.Web/Views/Calibration/Index.cshtml
@model IEnumerable<SSWA.CalibrationRegister.Web.Models.CalibrationListViewModel>
@using Microsoft.Extensions.Configuration;

@inject IConfiguration Configuration;

@{
    ViewData["Title"] = "Recent Calibrations";
}

<div class="row">
    <div class="col-md-12">
        <h3>Calibrations &rsaquo; Recent</h3>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        @Html.ActionLink("New Calibration", "Tag", "Calibration", null, new { @class = "btn btn-primary" })
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.RecordNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TagName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TagDescription)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TestedAt)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TestedBy)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PassFail)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.RecordNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TagName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TagDescription)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TestedAt)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TestedBy)
                        </td>
                        <td>
                            @if (item.PassFail && !item.VerificationOnly)
    {
                        <span class="text-success"><i class="glyphicon glyphicon-ok"></i> PASS</span>
}
else if (!item.PassFail && !item.VerificationOnly)
{
                        <span class="text-danger"><i class="glyphicon glyphicon-remove"></i> FAIL</span>
}
else
{
                        <span class="text-primary"><i class="glyphicon glyphicon-search"></i> VERIFICATION</span>

}
                        </td>
                        <td>
                            <a href="@Configuration["Reports:CalibrationUrl"]@item.ID" target="_blank">Certificate</a> |
                            @Html.ActionLink("Tag History", "History", "Calibration", new { tagId = item.TagID }, new { target = "_blank" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

SSWA.CalibrationRegister.Web/Views/Calibration/Tag.cshtml
@model SSWA.CalibrationRegister.Web.Models.TagListViewModel
@{
    ViewData["Title"] = "Tags";
}

<div class="row">
    <div class="col-md-12">
        <h3>Calibrations &rsaquo; Tags</h3>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h4>Search For A Tag</h4>
        @using (Html.BeginForm("Tag", "Calibration", FormMethod.Get, new { @class = "form-inline" }))
        {
            <div class="form-group">
                <label>Tag Type</label>
                @Html.DropDownList("tagTypeId", Model.TagTypeList, "", new { @class = "form-control input-sm" })
            </div>
            <div class="form-group">
                <label>Tag Name</label>
                @Html.TextBox("tagName", Model.TagName, null, new { @class = "form-control input-sm" })
            </div>
            <div class="form-group">
                <label>Tag Description</label>
                @Html.TextBox("tagDescription", Model.TagDescription, null, new { @class = "form-control input-sm" })
            </div>
            <div class="form-group">
                <input class="btn btn-sm btn-success" type="submit" value="Search" />
            </div>
        }
    </div>
    <div class="col-md-12">
        <hr />
    </div>

</div>
<div class="row">
    <div class="col-md-12">


        @{
            var prevDisabled = !Model.Tags.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.Tags.HasNextPage ? "disabled" : "";
        }
        <a asp-action="Index"
           asp-route-page="@(Model.Tags.PageIndex - 1)"
           asp-route-tagTypeId="@Model.TagTypeId"
           asp-route-tagName="@Model.TagName"
           asp-route-tagDescription="@Model.TagDescription"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-action="Index"
           asp-route-page="@(Model.Tags.PageIndex + 1)"
           asp-route-tagTypeId="@Model.TagTypeId"
           asp-route-tagName="@Model.TagName"
           asp-route-tagDescription="@Model.TagDescription"
           class="btn btn-default @nextDisabled">
            Next
        </a>
        <table class="table">
            <thead>
                <tr>
                    <th width="5%">
                        Tag Type
                    </th>
                    <th width="10%">
                        @Html.DisplayNameFor(model => model.Tags.FirstOrDefault().Name)
                    </th>
                    <th width="10%">
                        @Html.DisplayNameFor(model => model.Tags.FirstOrDefault().Description)
                    </th>
                    <th width="10%">
                        @Html.DisplayNameFor(model => model.Tags.FirstOrDefault().Make)
                    </th>
                    <th width="10%">
                        @Html.DisplayNameFor(model => model.Tags.FirstOrDefault().Model)
                    </th>
                    <th width="10%">
                        Serial Number
                    </th>
                    <th width="10%">
                        Reference Drawing
                    </th>
                    <th width="10%">
                        Procedure
                    </th>
                    <th width="10%">
                        Data Sheet
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Tags)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TagType.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Make)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Model)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SerialNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReferenceDrawing)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Procedure)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DataSheet)
                        </td>
                        <td width="20%">
                            @Html.ActionLink("New Calibration", "Create", new { tagId = item.ID }) |
                            @Html.ActionLink("History", "History", new { tagId = item.ID })                        
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>